In [28]:
#Print the shape of a 2-D array:

import numpy as np

arr = np.array([[1, 2, 3, 3], [5, 6, 7, 8]])

print(arr.shape)
#There are 2 horizontal lines-2 columns
#Each line has 4 numbers-4 columns
#shape = (2,4)

(2, 4)


In [6]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr)
print('shape of array :', arr.shape)

[1 2 3 4]
shape of array : (4,)


In [26]:
import numpy as np

arr = np.array([1, 2, 3, 2], ndmin=5) #here 5 represents 5 dimensions

print(arr)
print('shape of array :', arr.shape)


[[[[[1 2 3 2]]]]]
shape of array : (1, 1, 1, 1, 4)


#what does shape tuple represent-
* it reprsents the no of elemts each dimension has
* for ex :shape of array (1,1,1,1,4 )represents that the 5th diemention (4(1s)+1) 5th dimention has 4 (1,2,3,4) elements(column),(here 4 represents column and has 4 elements)

In [20]:
arr = np.array([1, 2, 3, 4, 5])

print(arr.
shape
)

(1, 1, 1, 5)


NumPy Array Reshaping.
* reshaping means changing the shape of the array i,e,.changing the dimension(adding and removal of dimensions also possible) *

In [29]:
#Reshape From 1-D to 2-D
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [30]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],ndmin=2)

print("1-D Array\n")

print(arr)

print("Shape of Array:",arr.shape)

print("\n2-D Array\n")

newarr = arr.reshape(4, 3)

print(newarr)

print("Reshaped Array:",newarr.shape)

1-D Array

[[ 1  2  3  4  5  6  7  8  9 10 11 12]]
Shape of Array: (1, 12)

2-D Array

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Reshaped Array: (4, 3)


 arr.reshape(2, 3, 2) =2,3,2 repreent 2array of 3,2 dimention

In [31]:
#Reshape From 1-D to 3-D
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2) #arr.reshape(2, 3, 2) =2,3,2 repreent 2array of 3,2 dimention

print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


can we have diff dimention with diff two array
* from existing 1d array it is not possible to have dif dimention with dif array
* but it is possible to have diff array with diff dimention from scratch

In [32]:
import numpy as np

# 1. Create a 1D array with 12 elements
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

# 2. Reshape to 3D: (Layers, Rows, Columns)
# 2 * 3 * 2 = 12 total elements
newarr = arr.reshape(2, 3, 2)

print("The 3D Array:")
print(newarr)

print("\n--- Shape Breakdown ---")
shape = newarr.shape
print(f"Full Shape: {shape}")
print(f"Number of Layers (Blocks): {shape[0]}")
print(f"Number of Rows per layer:  {shape[1]}")
print(f"Number of Columns per row: {shape[2]}")

The 3D Array:
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]

--- Shape Breakdown ---
Full Shape: (2, 3, 2)
Number of Layers (Blocks): 2
Number of Rows per layer:  3
Number of Columns per row: 2


# Copy or View?

In [33]:
#check if the returned array is a copy or a view:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

print(arr.reshape(2, 4).base)

[1 2 3 4 5 6 7 8]


this ex returns the original array i.e.,its a view

In [34]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = arr.copy()

arr[0] = 42

print(x.reshape(2, 4).base)

print(arr.reshape(2,4).base)

[1 2 3 4 5 6 7 8]
[42  2  3  4  5  6  7  8]


check if array owns its data

In [35]:
#Print the value of the base attribute to check if an array owns it's data or not:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)


None
[1 2 3 4 5]


# Flattening the arrays
* Flattening array means converting a multidimensional array into a 1D array.

* We can use reshape(-1) to do this.

In [36]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1)

print(newarr)

[1 2 3 4 5 6]


In [42]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

# This line caused the error: 2*2*2 = 8 elements, but array has 6 elements.
# newarr = arr.reshape(2,2,2)

# To fix, ensure the product of the new dimensions equals the original number of elements (6).
# For example, reshape to a 2D array of (2, 3) or (3, 2),
# or a 3D array like (1, 2, 3) or (2, 3, 1).
# Here's an example reshaping to (2, 3):
newarr = arr.reshape(2, 3)

print(newarr)

[[1 2 3]
 [4 5 6]]
