In [6]:
# 1. SUPERVISED LEARNING - Crop Classification
print("=== Supervised Learning Example ===")

# Training data: [temperature, rainfall] -> crop_suitable
training_data = [
    ([25, 100], "rice"),      # Warm, wet = rice
    ([30, 50], "wheat"),      # Warm, moderate = wheat
    ([20, 150], "rice"),      # Cool, very wet = rice
    ([35, 30], "millet"),     # Hot, dry = millet
]

def simple_crop_classifier(temp, rain):
    """Simple supervised learning model"""
    if rain > 100:
        return "rice"
    elif temp > 32 and rain < 40:
        return "millet"
    else:
        return "wheat"

# Test prediction
print(f"Temp=28, Rain=40mm -> {simple_crop_classifier(35, 30)}")

=== Supervised Learning Example ===
Temp=28, Rain=40mm -> millet


In [7]:
# 2. UNSUPERVISED LEARNING - Soil Clustering
print("\n=== Unsupervised Learning Example ===")

soil_samples = [
    {"pH": 6.5, "nitrogen": 80, "organic": 3.2},
    {"pH": 6.8, "nitrogen": 75, "organic": 3.0},
    {"pH": 5.2, "nitrogen": 40, "organic": 1.5},
    {"pH": 5.0, "nitrogen": 35, "organic": 1.2},
    {"pH": 7.5, "nitrogen": 90, "organic": 4.0},
]

def simple_soil_clustering(samples):
    """Group soils by pH level (simple clustering)"""
    clusters = {"acidic": [], "neutral": [], "alkaline": []}

    for i, sample in enumerate(samples):
        if sample["pH"] < 6.0:
            clusters["acidic"].append(f"Sample_{i}")
        elif sample["pH"] < 7.2:
            clusters["neutral"].append(f"Sample_{i}")
        else:
            clusters["alkaline"].append(f"Sample_{i}")

    return clusters

clusters = simple_soil_clustering(soil_samples)
print("Soil Clusters:", clusters)



=== Unsupervised Learning Example ===
Soil Clusters: {'acidic': ['Sample_2', 'Sample_3'], 'neutral': ['Sample_0', 'Sample_1'], 'alkaline': ['Sample_4']}


In [8]:
# 3. REINFORCEMENT LEARNING - Irrigation Simulation
print("\n=== Reinforcement Learning Concept ===")

class SimpleIrrigationAgent:
    """Learns irrigation timing through rewards"""

    def __init__(self):
        self.q_values = {"morning": 0, "afternoon": 0, "evening": 0}
        self.learning_rate = 0.1

    def get_action(self):
        # Choose best known action
        return max(self.q_values, key=self.q_values.get)

    def learn(self, action, reward):
        # Update knowledge based on reward
        self.q_values[action] += self.learning_rate * reward
        print(f"  Irrigated in {action}: reward = {reward}")

# Simulate learning
agent = SimpleIrrigationAgent()
rewards = {"morning": 10, "afternoon": -5, "evening": 8}

print("Learning optimal irrigation time...")
for episode in range(5):
    for time_slot, reward in rewards.items():
        agent.learn(time_slot, reward)

print(f"Best learned time: {agent.get_action()}")


=== Reinforcement Learning Concept ===
Learning optimal irrigation time...
  Irrigated in morning: reward = 10
  Irrigated in afternoon: reward = -5
  Irrigated in evening: reward = 8
  Irrigated in morning: reward = 10
  Irrigated in afternoon: reward = -5
  Irrigated in evening: reward = 8
  Irrigated in morning: reward = 10
  Irrigated in afternoon: reward = -5
  Irrigated in evening: reward = 8
  Irrigated in morning: reward = 10
  Irrigated in afternoon: reward = -5
  Irrigated in evening: reward = 8
  Irrigated in morning: reward = 10
  Irrigated in afternoon: reward = -5
  Irrigated in evening: reward = 8
Best learned time: morning


In [10]:
# Statistics with Farm Data
import statistics

# Annual yields (kg/hectare) for past 5 years
yields = [2500, 2500, 2500, 2500, 2500]

print("=== Yield Statistics ===")
print(f"Yields: {yields}")
print(f"Mean: {statistics.mean(yields):.0f} kg/ha")
print(f"Median: {statistics.median(yields):.0f} kg/ha")
print(f"Std Dev: {statistics.stdev(yields):.0f} kg/ha")
print(f"Range: {max(yields) - min(yields)} kg/ha")

# Probability calculation
total_years = 10
drought_years = 3
prob_drought = drought_years / total_years
print(f"\nDrought Probability: {prob_drought:.0%}")

# Variance interpretation
if statistics.stdev(yields) > 300:
    print("⚠️ High variability - consider crop insurance!")
else:
    print("✅ Stable yields - good predictability")

=== Yield Statistics ===
Yields: [2500, 2500, 2500, 2500, 2500]
Mean: 2500 kg/ha
Median: 2500 kg/ha
Std Dev: 0 kg/ha
Range: 0 kg/ha

Drought Probability: 30%
✅ Stable yields - good predictability


In [11]:

import numpy as np

# === CREATING ARRAYS ===
print("=== Creating NumPy Arrays ===")

# From list
yields = np.array([2500, 2800, 3100, 2900, 2700])
print(f"Yields: {yields}")
print(f"Type: {type(yields)}")

# Using arange (like range, but for arrays)
plot_numbers = np.arange(1, 6)
print(f"Plots: {plot_numbers}")

# Using linspace (evenly spaced)
temperatures = np.linspace(20, 35, 5)
print(f"Temperature range: {temperatures}")

# 2D Array (matrix) - farm grid
farm_grid = np.array([
    [2500, 2600, 2700],
    [2800, 2900, 3000],
    [2400, 2500, 2600]
])
print(f"\nFarm Grid:\n{farm_grid}")
print(f"Shape: {farm_grid.shape}")  # 3 rows, 3 columns

# === INDEXING AND SLICING ===
print("\n=== Indexing and Slicing ===")

# Access elements
print(f"First yield: {yields[0]}")
print(f"Last yield: {yields[-1]}")
print(f"First 3 yields: {yields[:3]}")

# 2D indexing
print(f"Center plot yield: {farm_grid[1, 1]}")
print(f"First row: {farm_grid[0]}")
print(f"Last column: {farm_grid[:, -1]}")

# === ARRAY OPERATIONS ===
print("\n=== Array Operations ===")

# Math on entire arrays (vectorized!)
yields_tons = yields / 1000
print(f"Yields in tons: {yields_tons}")

# Bonus calculation
bonus = np.where(yields > 2800, 500, 0)
print(f"Bonus per plot: {bonus}")

# Statistics
print(f"\nTotal yield: {np.sum(yields)} kg")
print(f"Average: {np.mean(yields):.0f} kg")
print(f"Std Dev: {np.std(yields):.0f} kg")
print(f"Max: {np.max(yields)} kg, Min: {np.min(yields)} kg")

# Boolean filtering
high_yield_plots = yields[yields > 2700]
print(f"High yield plots (>2700): {high_yield_plots}")


=== Creating NumPy Arrays ===
Yields: [2500 2800 3100 2900 2700]
Type: <class 'numpy.ndarray'>
Plots: [1 2 3 4 5]
Temperature range: [20.   23.75 27.5  31.25 35.  ]

Farm Grid:
[[2500 2600 2700]
 [2800 2900 3000]
 [2400 2500 2600]]
Shape: (3, 3)

=== Indexing and Slicing ===
First yield: 2500
Last yield: 2700
First 3 yields: [2500 2800 3100]
Center plot yield: 2900
First row: [2500 2600 2700]
Last column: [2700 3000 2600]

=== Array Operations ===
Yields in tons: [2.5 2.8 3.1 2.9 2.7]
Bonus per plot: [  0   0 500 500   0]

Total yield: 14000 kg
Average: 2800 kg
Std Dev: 200 kg
Max: 3100 kg, Min: 2500 kg
High yield plots (>2700): [2800 3100 2900]


In [12]:
import numpy as np
import statistics

# Farm data as matrix
# Columns: Temp, Rainfall, Soil_pH, Fertilizer
farm_data = np.array([
    [28, 150, 6.5, 50],  # Plot 1
    [30, 120, 6.8, 45],  # Plot 2
    [26, 180, 6.2, 60],  # Plot 3
    [29, 140, 6.6, 55],   # Plot 4
    [32,165,6.7,50 ] # plot 5
])

print("Farm Data Matrix:")
print(farm_data)
print(f"Shape: {farm_data.shape} (5 plots × 4 features)")

# Vector operations - weights for yield prediction
weights = np.array([10, 5, 100, 20])  # Importance of each feature

# Matrix-vector multiplication = predictions
base_yield = 1000
predictions = base_yield + farm_data @ weights

print("\nPredicted Yields:")
for i, pred in enumerate(predictions):
    print(f"Plot {i+1}: {pred:.0f} kg/ha")

print("=== Yield Statistics ===")
print(f"Yields: {predictions}")
print(f"Mean: {statistics.mean(predictions):.0f} kg/ha")
print(f"Median: {statistics.median(predictions):.0f} kg/ha")
print(f"Std Dev: {statistics.stdev(predictions):.0f} kg/ha")
print(f"Range: {max(predictions) - min(predictions)} kg/ha")

# Probability calculation
total_years = 10
drought_years = 3
prob_drought = drought_years / total_years
print(f"\nDrought Probability: {prob_drought:.0%}")

# Variance interpretation
if statistics.stdev(predictions) > 300:
    print("⚠️ High variability - consider crop insurance!")
else:
    print("✅ Stable yields - good predictability")

Farm Data Matrix:
[[ 28.  150.    6.5  50. ]
 [ 30.  120.    6.8  45. ]
 [ 26.  180.    6.2  60. ]
 [ 29.  140.    6.6  55. ]
 [ 32.  165.    6.7  50. ]]
Shape: (5, 4) (5 plots × 4 features)

Predicted Yields:
Plot 1: 3680 kg/ha
Plot 2: 3480 kg/ha
Plot 3: 3980 kg/ha
Plot 4: 3750 kg/ha
Plot 5: 3815 kg/ha
=== Yield Statistics ===
Yields: [3680. 3480. 3980. 3750. 3815.]
Mean: 3741 kg/ha
Median: 3750 kg/ha
Std Dev: 183 kg/ha
Range: 500.0 kg/ha

Drought Probability: 30%
✅ Stable yields - good predictability
