#NumPy Splitting Array = array_split()
* splitting breaks one array into multiple arrays
* the total no of elements in 1D array should be divisible by the no of elements
* We use array_split() for splitting arrays, we pass it the array we want to split and the number of splits.
* if elements are even then split will be even otherwise the no of splits will be uneven
* note:the diff b/w split fn and array_fn is that split fn only gives the output when the no elements divisble by no of splits in this scenerio split fn gives the output when the no of spits are 1,2,

In [ ]:
#Split the array in 3 parts:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


note:the diff b/w split fn and array_fn is that split fn only gives the output when the no elements divisble by no of splits in this scenerio split fn gives the output when the no of spits are 1,2,3,6 and not 4,5,

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.split(arr, 6)

print(newarr)

[array([1]), array([2]), array([3]), array([4]), array([5]), array([6])]


# Split Into Arrays = array_split()
* split into array and store the splitted array into 3 array

In [ ]:
#Access the splitted arrays:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr[0])
print(newarr[1])
print(newarr[2])

[1 2]
[3 4]
[5 6]


In [ ]:
#Access the splitted arrays:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 7)

print(newarr[0:3])


#Splitting 2-D Arrays
Use the same syntax when splitting 2-D arrays.

Use the array_split() method, pass in the array you want to split and the number of splits you want to do.

In [ ]:
#Split the 2-D array into three 2-D arrays.

import numpy as np

arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [ ]:
#Split the 2-D array into three 2-D arrays.

import numpy as np

arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 4)

print(newarr[0])
print(newarr[1])
print(newarr[2])
print(newarr[3])

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[ 9 10]]
[[11 12]]


In [ ]:
#Split the 2-D array into three 2-D arrays.

import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3)

print(newarr)


[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


The example above returns three 2-D arrays.

In addition, you can specify which axis you want to do the split around.

The example below also returns three 2-D arrays, but they are split along the column (axis=1).

in array_split if ax=0,gives the same output i.w,along rows

if ax=1,ie., split along columns hsplit gives same output

In [1]:
#Split the 2-D array into three 2-D arrays along columns.

import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3, axis=0)

print(newarr)


[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


in array_split if ax=0,gives the same output i.w,along rows

if ax=1,ie., split along columns hsplit gives same output

In [ ]:
# the hsplit() method to split the 2-D array into three 2-D arrays along columns.

import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.hsplit(arr, 3)

print(newarr)


[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]
