# NumPy Joining Array
* Joining means putting contents of two or more arrays in a single array.
* in Numpy we use concatenate() to join
* note:here by default axis = 0,which means the output is printed Rowwise (stack vertically)
* access value also be one which is demonstrated in 2D array joining or concatination

In [1]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [6]:
#Join two 2-D arrays along rows (axis=1):

import numpy as np

arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1) #ax = 1 represents that the output is printed columnwise(horizontal or side ways)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


* Expaination of axis fn
when axis = 1,columns are taken and ---> sideways or horizontal appending is carried out,
* when axis = 0 ,rows are taken and down symbol,i.e.,downwards or vertically,down rows appending is done

**consider two students having two subject marks as follows**
* student1 = 50,60
* student2 = 70,80
* q1. print the sum of marks using numpy along with axis fn
* a>axis = 0  
* b>axis = 1
* print max marks

In [7]:
import numpy as np

marks = np.array([[50, 60], [70, 80]])

print("Marks array:")
print(marks)

print("\nSum of marks along axis=0 (column-wise sum):")
print(np.sum(marks, axis=0))

print("\nSum of marks along axis=1 (row-wise sum):")
print(np.sum(marks, axis=1))

print("\nMaximum mark overall:")
print(np.max(marks))

Marks array:
[[50 60]
 [70 80]]

Sum of marks along axis=0 (column-wise sum):
[120 140]

Sum of marks along axis=1 (row-wise sum):
[110 150]

Maximum mark overall:
80


In [8]:
import numpy as np

# Marks of 2 students in 2 subjects
marks = np.array([[50, 60],
                  [70, 80]])

# Student-wise total (axis=1)
student_total = np.sum(marks, axis=1)
print("Student-wise total:", student_total)

# Subject-wise total (axis=0)
subject_total = np.sum(marks, axis=0)
print("Subject-wise total:", subject_total)

# Student-wise maximum marks
student_max = np.max(marks, axis=1)
print("Student-wise maximum:", student_max)

Student-wise total: [110 150]
Subject-wise total: [120 140]
Student-wise maximum: [60 80]


#joining Arrays Using Stack Functions
* Stacking is same as concatenation, the only difference is that stacking is done along a new axis

In [11]:
#joining 2 1D array
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)

print(arr)


[[1 4]
 [2 5]
 [3 6]]


* note:if stack is used to join 2 1d array ax= 0 arranges the arrays horizontally and appends them
* but ax = 1,stack arranges the arrays vertically and appends them

#Stacking Along Rows
Numpy provides Helper fn :hstack() to stack along rows.

In [12]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


# Stacking Along Columns
* NumPy provides a helper function: vstack()  to stack along columns

In [13]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))

print(arr)

[[1 2 3]
 [4 5 6]]


**Stacking Along Height (depth)**
NumPy provides a helper function: dstack() to stack along height, which is the same as depth

In [14]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.dstack((arr1, arr2))

print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


In [15]:
import numpy as np

# Crop yields for 4 farms over 5 seasons (in tons)
crop_yields = np.array([
    [12.5, 13.2, 14.1, 13.8, 15.2],  # Farm 1 - North Region
    [10.3, 11.5, 10.8, 12.1, 11.9],  # Farm 2 - South Region
    [15.1, 14.8, 16.2, 15.5, 16.8],  # Farm 3 - East Region
    [11.2, 10.9, 12.3, 11.7, 12.8]   # Farm 4 - West Region
])

print('Crop Yields Array (tons):')
print(crop_yields)
print(f'\nShape: {crop_yields.shape}')
print(f'Data type: {crop_yields.dtype}')
print(f'Total elements: {crop_yields.size}')
print(f'Number of dimensions: {crop_yields.ndim}')

# Agricultural analysis operations
total_yield = np.sum(crop_yields)
avg_yield_per_farm = np.mean(crop_yields, axis=1)
avg_yield_per_season = np.mean(crop_yields, axis=0)
max_yield = np.max(crop_yields)
min_yield = np.min(crop_yields)

print(f'\nTotal production: {total_yield} tons')
print(f'Average per farm: {avg_yield_per_farm} tons')
print(f'Average per season: {avg_yield_per_season} tons')
print(f'Maximum yield: {max_yield} tons')
print(f'Minimum yield: {min_yield} tons')

# Find best performing farm
best_farm = np.argmax(avg_yield_per_farm)
print(f'\nBest performing farm: Farm {best_farm + 1}')
print(f'Their average yield: {avg_yield_per_farm[best_farm]:.2f} tons')

Crop Yields Array (tons):
[[12.5 13.2 14.1 13.8 15.2]
 [10.3 11.5 10.8 12.1 11.9]
 [15.1 14.8 16.2 15.5 16.8]
 [11.2 10.9 12.3 11.7 12.8]]

Shape: (4, 5)
Data type: float64
Total elements: 20
Number of dimensions: 2

Total production: 262.7 tons
Average per farm: [13.76 11.32 15.68 11.78] tons
Average per season: [12.275 12.6   13.35  13.275 14.175] tons
Maximum yield: 16.8 tons
Minimum yield: 10.3 tons

Best performing farm: Farm 3
Their average yield: 15.68 tons
