#NumPy Array Iterating
* In Numpy array iteration is crried out using diff loping constructs like FOR,WHILE,DO WHILE
* we are checking through elements one by one and execution stops only when condition becomes false i.e,come out of loop

In [1]:
# iterate on the elements on 1D array
import numpy as np

arr = np.array([1, 2, 3])

for x in arr:
  print(x)

1
2
3


note:For multidimentional arrays the execution works in the following manner

In [2]:
# iterate on the elements on 2D array
# here it will go through all the rows
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  print(x)

[1 2 3]
[4 5 6]


In [4]:
#Iterate on the elements of the following 3-D array:
import numpy as np
                                                                     #arr[2,2.3]
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])  #0-123456,1-789101112
                                                                     #arr[0,0,0] = 1
for x in arr:
  print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [ ]:
#arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
 #           x=0                x=1
#      y=0    y=1
#z=0(v=1) z=1(v=2) z=2(v=3)
x = [[[1, 2, 3], [4, 5, 6]]
y = [[1, 2, 3]
z = 1

#Iterating Arrays Using nditer()
the function helps in iterations from basic to advance operations

In [5]:
import numpy as np

# Using nditer
arr = np.array([[1, 2], [3, 4]])

for element in np.nditer(arr):
    print(element)

1
2
3
4


In basic for loops, iterating through each scalar of an array we need to use n for loops which can be difficult to write for arrays with very high dimensionality.

In [6]:
#Iterate through the following 3-D array
import numpy as np

arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


Iterating Array With Different Data Types

In [7]:
#Iterate through the array as a string:
import numpy as np

arr = np.array([1, 2, 3])

for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
  print(x)

np.bytes_(b'1')
np.bytes_(b'2')
np.bytes_(b'3')


Here the integer array elements are converted into string by using  op_dtypes = ['s'] and Here it reqires some space(buffer space) to perform this action and in order to enable it in nditer() we pass flags=['buffered']
* note : size of diff data type in python  https://docs.oracle.com/cd/E19253-01/817-6223/chp-typeopexpr-2/index.html

in nditer function ,by default array elements are displayed in row wise
* if the elements have to be displayed in colum wise include the argument order = f inside ndter
* any how array elements are printed in row wise but expilcitly sing order  ndter fn can be given as order = c
row major order: 'c'
[1 2
 3  4]
 * output;
 1
 2
 3
 4
 * column major order: 'f'
 [1 3
  2 4 ]
  1
  3
  2
  4

In [8]:
import numpy as np

arr = np.array([[1, 2], [3, 4]])

for element in np.nditer(arr, order='F'):
    print(element)

1
3
2
4


In [9]:
import numpy as np

arr = np.array([[1, 2], [3, 4]])

for element in np.nditer(arr, order='C'):
    print(element)

1
2
3
4


In [10]:
import numpy as np

arr = np.array([[1, 2], [3, 4]])

print("The original 2D array:")
print(arr)

fortran_elements = []
for element in np.nditer(arr, order='F'):
    fortran_elements.append(element)

fortran_ordered_2d = np.array(fortran_elements).reshape(arr.shape)

print("\nElements in Fortran order (reshaped to 2D):")
print(fortran_ordered_2d)

The original 2D array:
[[1 2]
 [3 4]]

Elements in Fortran order (reshaped to 2D):
[[1 3]
 [2 4]]


In [11]:
import numpy as np

arr = np.array([[1, 2], [3, 4]])

# Get elements in Fortran order and reshape them into a 2D array
fortran_ordered_2d = arr.flatten(order='F').reshape(arr.shape)

print("Elements in Fortran order (reshaped to 2D):")
print(fortran_ordered_2d)

Elements in Fortran order (reshaped to 2D):
[[1 3]
 [2 4]]


Iterating With Different Step Size

In [15]:
#Iterating With Different Step Size
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for x in np.nditer(arr[:, ::3]):
  print(x)

1
4
5
8


Enumerated Iteration Using ndenumerate()\
* gives the indexing or position of the element in the array

In [17]:
#Enumerate on following 1D arrays elements:
import numpy as np

arr = np.array([1, 2, 3])

for idx, x in np.ndenumerate(arr):
  print(idx, x)


(0,) 1
(1,) 2
(2,) 3


In [18]:

#Enumerate on following 2D array's elements:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


In [19]:
import numpy as np

# Create a 2D array
arr = np.array([[10, 20], [30, 40]])

# Enumerate through rows
for idx, row in enumerate(arr):
    print(f"Row {idx}: {row}")

Row 0: [10 20]
Row 1: [30 40]
