In [ ]:
import numpy as np
print(np.__version__)

2.0.2


In [ ]:
# From Python list
arr = np.array([1, 2, 3, 4, 5])

# 2D array (matrix)
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])

# Using built-in functions
zeros = np.zeros((3, 4))         # 3x4 array of zeros
ones = np.ones((2, 3))           # 2x3 array of ones
range_arr = np.arange(0, 10, 2)  # [0, 2, 4, 6, 8]
linspace = np.linspace(0, 1, 5)  # 5 evenly spaced values from 0 to 1
identity = np.eye(3)             # 3x3 identity matrix
random_arr = np.random.rand(3, 4)# Random values between 0 and 1

In [ ]:
display(arr)

array([1, 2, 3, 4, 5])

In [ ]:
display(arr_2d)

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
zeros=np.zeros((3,4))

In [ ]:
display(zeros)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
display(ones)

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
#create an array
arr= np.arange(5 , 10)
print(arr)

[5 6 7 8 9]


In [ ]:
#generate sequence of no from 5 to14
arr= np.arange(5,14,2)
print(arr)

[ 5  7  9 11 13]


**display and print function are used as output function,display also sows th data type**

In [ ]:
#generate seqence of floating point numbers with step 0.2
sequence = np.arange(0, 1, 0.2)
print(sequence)


[0.  0.2 0.4 0.6 0.8]


In [ ]:
#generate a sequence and filter basic 0 to 20
sequence=np.arange(0,20,2)


In [ ]:
display(sequence)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
#filter sequence
filtered = sequence[sequence > 10]
print("Filtered Sequence:", filtered)

Filtered Sequence: [12 14 16 18]


**line space is a built in library function in numpy which returns a evenly spaced no over a specifid range
#diff b/w array and range
line space generates no with specific space


**if only 1 no is given in start and stop it will considr start default value as 0

In [ ]:
linspace = np.linspace(0,10,5)


In [ ]:
display(linspace)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [ ]:
sequence = np.arange(0 , 10, 5)


In [ ]:
display(sequence)

array([0, 5])

arrange fn discludes last no /stop no /end point
**whreas linspace includes it default
**if end as to be discluded (if end point = false)

In [ ]:
a_wt_e = np.linspace(0, 10, 10,)
print(a_wt_e)

[ 0.          1.11111111  2.22222222  3.33333333  4.44444444  5.55555556
  6.66666667  7.77777778  8.88888889 10.        ]


In [ ]:
a_wt_e = np.linspace(0, 10, 10, endpoint=False)
print(a_wt_e)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [ ]:
display (a_wt_e)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

to return the step b/w each no,**use retstep=True**

In [ ]:
array, step = np.linspace(0, 10, num=5, retstep=True)
print(array)
print("step size:", step)

[ 0.   2.5  5.   7.5 10. ]
step size: 2.5


**Multi Dimensional Arrays**

* for specifying dimensions in matrix **(Row and Column)** it is called shape in python



In [ ]:
array_2d = np.linspace(0,1,num=25)
print(array_2d)

[0.         0.04166667 0.08333333 0.125      0.16666667 0.20833333
 0.25       0.29166667 0.33333333 0.375      0.41666667 0.45833333
 0.5        0.54166667 0.58333333 0.625      0.66666667 0.70833333
 0.75       0.79166667 0.83333333 0.875      0.91666667 0.95833333
 1.        ]


row and column will be equal

In [ ]:
array_2d = np.linspace(0,1,num=25).reshape(5,5)
print(array_2d)

[[0.         0.04166667 0.08333333 0.125      0.16666667]
 [0.20833333 0.25       0.29166667 0.33333333 0.375     ]
 [0.41666667 0.45833333 0.5        0.54166667 0.58333333]
 [0.625      0.66666667 0.70833333 0.75       0.79166667]
 [0.83333333 0.875      0.91666667 0.95833333 1.        ]]


### `range()` Function

`range()` is a built-in Python function that generates a sequence of integers. It's primarily used for looping a specific number of times and for creating sequences of integers when you need a basic iterable.

In [ ]:
print('--- Using range() ---')

# Example with integers
sequence_range = range(0, 5) # Generates numbers from 0 up to (but not including) 5
print(f"range(0, 5): {list(sequence_range)}")
print(f"Type of range(0, 5): {type(sequence_range)}")

# range() does not support floating-point numbers
try:
    range_float = range(0, 1, 0.5)
except TypeError as e:
    print(f"\nError when using floats with range(): {e}")

--- Using range() ---
range(0, 5): [0, 1, 2, 3, 4]
Type of range(0, 5): <class 'range'>

Error when using floats with range(): 'float' object cannot be interpreted as an integer


### `np.arange()` Function

`np.arange()` is a NumPy function that also generates sequences of numbers. However, it's more versatile, capable of generating sequences with floating-point numbers and returning a NumPy array, which is highly optimized for numerical operations.

In [ ]:
import numpy as np

print('\n--- Using np.arange() ---')

# Example with integers
sequence_arange_int = np.arange(0, 5)
print(f"np.arange(0, 5): {sequence_arange_int}")
print(f"Type of np.arange(0, 5): {type(sequence_arange_int)}")

# Example with floating-point numbers
sequence_arange_float = np.arange(0.0, 1.0, 0.2)
print(f"np.arange(0.0, 1.0, 0.2): {sequence_arange_float}")
print(f"Type of np.arange(0.0, 1.0, 0.2): {type(sequence_arange_float)}")


--- Using np.arange() ---
np.arange(0, 5): [0 1 2 3 4]
Type of np.arange(0, 5): <class 'numpy.ndarray'>
np.arange(0.0, 1.0, 0.2): [0.  0.2 0.4 0.6 0.8]
Type of np.arange(0.0, 1.0, 0.2): <class 'numpy.ndarray'>


### Key Differences:

1.  **Return Type**: `range()` returns a `range` object (an iterator that generates numbers on the fly), while `np.arange()` returns a NumPy `ndarray`.
2.  **Data Types**: `range()` only works with integers. `np.arange()` can handle both integers and floating-point numbers.
3.  **Memory Usage**: `range()` is memory-efficient because it generates numbers as needed (lazy evaluation). `np.arange()` creates an array in memory containing all the numbers immediately.
4.  **Functionality**: `np.arange()` provides the full power of NumPy arrays, allowing for vectorized operations, advanced indexing, and integration with other NumPy functions, which `range()` does not.

In [ ]:
item = range(0, 10)
print(list(item))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [ ]:
print(list(item))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [ ]:
sequence = np.arange(0, 10)

In [ ]:
display(sequence)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# 2D Array (matrix) - farm grid
import numpy as np
farm_grid = np.array([
    [2500, 2600, 2700],
    [2800, 2900, 3000],
    [2400, 2500, 2600]
])
print(f"\nFarm Grid:\n{farm_grid}")
print(f"Shape: {farm_grid.shape}")  # 3 rows, 3 columns


Farm Grid:
[[2500 2600 2700]
 [2800 2900 3000]
 [2400 2500 2600]]
Shape: (3, 3)


**Numpy array indexing in order to acces an arry element indexing is used which stars from zero**

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[1])

2


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[2] + arr[3])

7


note:Table[rows,colums]
2d array  [2,3]

In [ ]:
#Access the third element of the second array of the first array:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2nd element on 1st row: ', arr[1, 2])

2nd element on 1st row:  8


**Accesing 3d array-*to access elements of 3d array use coomma separeted array representing dimensions and index*

In [ ]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])


6


In [ ]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[1, -1])


Last element from 2nd dim:  10


In [ ]:
yields = np.array([2500, 2800, 3100, 2900, 2700])

# Access elements
print(f"First yield: {yields[0]}")
print(f"Last yield: {yields[-1]}")
print(f"First 3 yields: {yields[:3]}")

First yield: 2500
Last yield: 2700
First 3 yields: [2500 2800 3100]


#slicing

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])

[2 3 4 5]


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[4:])

[5 6 7]


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-3:-1])


[5 6]


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[0:7:2])


[1 3 5 7]


#Slicing 2-D Arrays

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])

[7 8 9]


In [ ]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 2])

[3 8]


In [ ]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[::2])


[1 3 5 7]


In [ ]:
#Checking the Data Type of an Array
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr.dtype)

int64


In [ ]:
import numpy as np

arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype)


<U6


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [ ]:

import numpy as np

# 10 soil samples with pH values
soil_ph = np.array([6.2, 5.8, 7.1, 6.5, 5.5,
                    6.8, 7.3, 6.0, 5.9, 6.7])

# Your tasks:
# 1. Find the mean pH
# 2. Count samples that are acidic (pH < 6.5)
# 3. Find which sample has the highest pH
# 4. Normalize pH to 0-1 range using (x - min)/(max - min)


In [9]:
import numpy as np
# 10 soil samples with pH values
soil_ph = np.array([6.2, 5.8, 7.1, 6.5, 5.5,
                    6.8, 7.3, 6.0, 5.9, 6.7])
# 1. Find the mean pH
mean_ph = np.mean(soil_ph)
print(f"Mean pH: {mean_ph:.2f}")

Mean pH: 6.38


In [10]:
import numpy as np
# 10 soil samples with pH values
soil_ph = np.array([6.2, 5.8, 7.1, 6.5, 5.5,
                    6.8, 7.3, 6.0, 5.9, 6.7])
# 2. Count samples that are acidic (pH < 6.5)
acidic_samples_count = np.sum(soil_ph < 6.5)
print(f"Number of acidic samples (pH < 6.5): {acidic_samples_count}")

Number of acidic samples (pH < 6.5): 5


In [11]:
import numpy as np
# 10 soil samples with pH values
soil_ph = np.array([6.2, 5.8, 7.1, 6.5, 5.5,
                    6.8, 7.3, 6.0, 5.9, 6.7])
# 3. Find the highest pH
highest_ph = np.max(soil_ph)
print(f"Highest pH: {highest_ph:.2f}")

Highest pH: 7.30


In [12]:
import numpy as np
# 10 soil samples with pH values
soil_ph = np.array([6.2, 5.8, 7.1, 6.5, 5.5,
                    6.8, 7.3, 6.0, 5.9, 6.7])
# 4. Normalize pH to 0-1 range
min_ph = np.min(soil_ph)
max_ph = np.max(soil_ph)
normalized_ph = (soil_ph - min_ph) / (max_ph - min_ph)
print(f"Normalized pH values: {normalized_ph}")

Normalized pH values: [0.38888889 0.16666667 0.88888889 0.55555556 0.         0.72222222
 1.         0.27777778 0.22222222 0.66666667]


In [13]:
import numpy as np

# Creating a rank 1 Array
arr = np.array([1, 2, 3])
print(arr)

# Creating a rank 2 Array
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
print(arr)

# Creating an array from tuple
arr = np.array((1, 3, 2))
print(arr)

[1 2 3]
[[1 2 3]
 [4 5 6]]
[1 3 2]


In [14]:
arr = np.array([[-1, 2, 0, 4],
                [4, -0.5, 6, 0],
                [2.6, 0, 7, 8],
                [3, -7, 4, 2.0]])

# Printing a range of Array
# with the use of slicing method
arr2 = arr[2:, 1::2]
print ("last 2 rows and alternate columns(1 and 3):\n", arr2)

last 2 rows and alternate columns(1 and 3):
 [[ 0.  8.]
 [-7.  2.]]


In [15]:
# Printing elements at
# specific Indices
arr = np.array([[-1, 2, 0, 4],
                [4, -0.5, 6, 0],
                [2.6, 0, 7, 8],
                [3, -7, 4, 2.0]])

arr3 = arr[[1, 1, 0, 3],
                [3, 2, 1, 0]]
print ("\nElements at indices (1, 3), "
    "(1, 2), (0, 1), (3, 0):\n", arr3)


Elements at indices (1, 3), (1, 2), (0, 1), (3, 0):
 [0. 6. 2. 3.]


In [16]:
# Printing elements at
# specific Indices
arr = np.array([[-1, 2, 0, 4],
                [4, -0.5, 6, 0],
                [2.6, 0, 7, 8],
                [3, -7, 4, 2.0]])

arr3 = arr[[1, 1, 0, 3],
                [3, 2, 1, 0]]
print ("\nElements at indices (1, 3), "
    "(1, 2), (0, 1), (3, 0):\n", arr3)

arr4 = arr[1,3]
print("\nElements at index (1, 3) is",arr4)

arr5 = arr[1,2]
print("\nElements at index (1, 2) is",arr5)

arr6 = arr[0,1]
print("\nElements at index (0, 1) is",arr6)

arr7 = arr[3,0]
print("\nElements at index (3, 0) is",arr7)


Elements at indices (1, 3), (1, 2), (0, 1), (3, 0):
 [0. 6. 2. 3.]

Elements at index (1, 3) is 0.0

Elements at index (1, 2) is 6.0

Elements at index (0, 1) is 2.0

Elements at index (3, 0) is 3.0


#Basic Array Operations
In numpy, arrays allow a wide range of operations which can be performed on a particular array or a combination of Arrays. These operation include some basic Mathematical operation as well as Unary and Binary operations.

In [17]:
import numpy as np

# Defining Array 1
a = np.array([[1, 2],
              [3, 4]])

# Defining Array 2
b = np.array([[4, 3],
              [2, 1]])

# Adding 1 to every element
print ("Adding 1 to every element:", a + 1)

# Subtracting 2 from each element
print ("\nSubtracting 2 from each element:", b - 2)

# sum of array elements
# Performing Unary operations
print ("\nSum of all array elements: ", a.sum())

# Adding two arrays
# Performing Binary operations
print ("\nArray sum:\n", a + b)

Adding 1 to every element: [[2 3]
 [4 5]]

Subtracting 2 from each element: [[ 2  1]
 [ 0 -1]]

Sum of all array elements:  10

Array sum:
 [[5 5]
 [5 5]]


In [20]:
import numpy as np

# Integer datatype
x = np.array([1, 2])
print(x.dtype)

# Float datatype
x = np.array([1.0, 2.0])
print(x.dtype)

# Forced Datatype
x = np.array([1.0, 2.1], dtype = np.int64)
print(x.dtype)

int64
float64
int64


#Math Operations on DataType array
In Numpy arrays, basic mathematical operations are performed element-wise on the array. These operations are applied both as operator overloads and as functions. Many useful functions are provided in Numpy for performing computations on Arrays such as sum: for addition of Array elements, T: for Transpose of elements, etc.
*note:daigonal remains same
opp of daigonal reverse*






In [21]:
#sum
import numpy as np

# First Array
arr1 = np.array([[4, 7], [2, 6]],
                 dtype = np.float64)

# Second Array
arr2 = np.array([[3, 6], [2, 8]],
                 dtype = np.float64)

# Addition of two Arrays
Sum = np.add(arr1, arr2)
print(Sum)

# Addition of all Array elements
Sum1 = np.sum(arr1)
print(Sum1)

# Square root of Array
Sqrt = np.sqrt(arr1)
print(Sqrt)

# Transpose of Array
Trans_arr = arr1.T
print(Trans_arr)

[[ 7. 13.]
 [ 4. 14.]]
19.0
[[2.         2.64575131]
 [1.41421356 2.44948974]]
[[4. 2.]
 [7. 6.]]


In [24]:
yields = np.array([2500, 2800, 3100, 2900, 2700])

farm_grid = np.array([
    [2500, 2600, 2700],
    [2800, 2900, 3000],
    [2400, 2500, 2600]
])

# === ARRAY OPERATIONS ===
print("\n=== Array Operations ===")

# Math on entire arrays (vectorized!)
yields_tons = yields / 1000
print(f"Yields in tons: {yields_tons}")

# Bonus calculation
bonus = np.where(yields > 2800, 500, 0)
print(f"Bonus per plot: {bonus}")

# Statistics
print(f"\nTotal yield: {np.sum(yields)} kg")
print(f"Average: {np.mean(yields):.0f} kg")
print(f"Std Dev: {np.std(yields):.0f} kg")
print(f"Max: {np.max(yields)} kg, Min: {np.min(yields)} kg")

# Boolean filtering
high_yield_plots = yields[yields > 2700]
print(f"High yield plots (>2700): {high_yield_plots}")

low_yield_plots = yields[yields < 2700]
print(f"Low yield plots (<2700): {low_yield_plots}")


=== Array Operations ===
Yields in tons: [2.5 2.8 3.1 2.9 2.7]
Bonus per plot: [  0   0 500 500   0]

Total yield: 14000 kg
Average: 2800 kg
Std Dev: 200 kg
Max: 3100 kg, Min: 2500 kg
High yield plots (>2700): [2800 3100 2900]
Low yield plots (<2700): [2500]


#numpy copy and view function
*dff b/w

In [25]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print(arr)
x = arr.view()
x[0] = 31


print(x)

[1 2 3 4 5]
[31  2  3  4  5]


note:copy function owns the data
*view will return original data*
