#NumPy Searching Arrays = where()
In numpy searching for a element in the array is done by where()

In [4]:
#Find the indexes where the value is 4:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

(array([3, 5, 6]),)


In [6]:
#Find the indexes where the values are even:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 0)

print(x)

(array([1, 3, 5, 7]),)


#Search Sorted = searchsorted()
* there is an array consisting of sorted elements
* if element exists,it returns index posn
* if doesnt exist it returns index where it has to be inserted



In [9]:
#Find the indexes where the value 7 should be inserted:

import numpy as np

arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 8)

print(x)


2


#Search From the Right Side
by default search happens from left side but if you want search from right side give side='right'

In [10]:
#Find the indexes where the value 7 should be inserted, starting from the right:

import numpy as np

arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7, side='right')

print(x)

2


In [11]:
#To search for more than one value, use an array with the specified value
#Find the indexes where the values 2, 4, and 6 should be inserted:

import numpy as np

arr = np.array([1, 3, 5, 7])

x = np.searchsorted(arr, [2, 4, 6])

print(x)

[1 2 3]
